export { default as MainPage } from "./main"
export { default as FaqsPage } from "./faq"
export { default as AboutPage } from "./about"
export { default as ContactPage } from "./contact"
export { default as RedirectPage } from "./redirect"